// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebSiteTest.Areas.supplier.Models
{
    public partial class Advertises
    {
        public int Adid { get; set; }
        public string Adtitle { get; set; }
        public string Adcontent { get; set; }
        public DateTime Adstart { get; set; }
        public DateTime Adend { get; set; }
        public string Adpicture { get; set; }
        public string Employee { get; set; }
        public int? Adviews { get; set; }
    }
}