// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace WebSiteTest.Areas.supplier.Models
{
    public partial class ComperWebSiteContext : DbContext
    {
        public ComperWebSiteContext()
        {
        }

        public ComperWebSiteContext(DbContextOptions<ComperWebSiteContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Advertises> Advertises { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Advertises>(entity =>
            {
                entity.HasKey(e => e.Adid)
                    .HasName("PK_AD");

                entity.ToTable("ADvertises");

                entity.Property(e => e.Adid).HasColumnName("ADId");

                entity.Property(e => e.Adcontent)
                    .IsRequired()
                    .HasColumnName("ADContent");

                entity.Property(e => e.Adend)
                    .HasColumnType("datetime")
                    .HasColumnName("ADEnd");

                entity.Property(e => e.Adpicture)
                    .IsRequired()
                    .HasColumnName("ADPicture");

                entity.Property(e => e.Adstart)
                    .HasColumnType("datetime")
                    .HasColumnName("ADStart");

                entity.Property(e => e.Adtitle)
                    .IsRequired()
                    .HasColumnName("ADtitle");

                entity.Property(e => e.Adviews).HasColumnName("ADviews");

                entity.Property(e => e.Employee).HasMaxLength(50);
            });

            modelBuilder.Entity<Suppliers>(entity =>
            {
                entity.HasKey(e => e.SupplierId);

                entity.Property(e => e.SupplierId).HasColumnName("SupplierID");

                entity.Property(e => e.Account)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Address)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Bank)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.CompanyName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.ContactPerson).HasMaxLength(50);

                entity.Property(e => e.Email)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Phone).HasMaxLength(50);

                entity.Property(e => e.UniformNumbers)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("Uniform_numbers");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}