// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebSiteTest.Areas.supplier.Models
{
    public partial class Suppliers
    {
        public int SupplierId { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string ContactPerson { get; set; }
        public string Email { get; set; }
        public string Bank { get; set; }
        public string Account { get; set; }
        public string UniformNumbers { get; set; }
    }
}