// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebSiteTest.Areas.GpuComparison.Models
{
    public partial class ComputerModel
    {
        public string ProductsId { get; set; }
        public string Value { get; set; }
    }
}