// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebSiteTest.Areas.GpuComparison.Models
{
    public partial class GpuComparisonSystem
    {
        public string ProductsId { get; set; }
        public string _4kMark { get; set; }
        public string FhdMark { get; set; }
        public string BaseMark { get; set; }
        public string FfxivMark { get; set; }
        public string Temperature { get; set; }
        public string Price { get; set; }
        public DateTime? RunningDate { get; set; }
        public string Img { get; set; }
    }
}