// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebSiteTest.Areas.ThriftShop.Models
{
    public partial class ThriftShopOrderDetail
    {
        public string ThriftOrderId { get; set; }
        public string ThriftProductId { get; set; }
        public int ThriftProductQty { get; set; }
        public int ThriftProductUnitPrice { get; set; }

        public virtual ThriftShopOrders ThriftOrder { get; set; }
        public virtual ThriftProducts ThriftProduct { get; set; }
    }
}