// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebSiteTest.Areas.ThriftShop.Models
{
    public partial class ThriftShopOrders
    {
        public string ThriftOrderId { get; set; }
        public string ThriftCustomerId { get; set; }
        public string ThriftEmployeeId { get; set; }
        public DateTime ThriftOrderDate { get; set; }
        public DateTime ThriftShipDate { get; set; }
        public string ThriftOrderStatus { get; set; }
        public string ThriftShipAddress { get; set; }
        public string ShippingMethod { get; set; }

        public virtual ThriftShopOrderDetail ThriftShopOrderDetail { get; set; }
    }
}