// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebSiteTest.Areas.ThriftShop.Models
{
    public partial class ThriftPurchaseDetail
    {
        public string ThriftPurchaseId { get; set; }
        public string ThriftName { get; set; }
        public int ThriftQuantity { get; set; }
        public string ThriftNote { get; set; }
        public int ThriftPrice { get; set; }

        public virtual ThriftPurchase ThriftPurchase { get; set; }
    }
}