// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebSiteTest.Areas.ThriftShop.Models
{
    public partial class ThriftFavoriteList
    {
        public string CustomerId { get; set; }
        public string ThriftProductId { get; set; }
    }
}