// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebSiteTest.Areas.ProductsManager.Models
{
    public partial class Customers
    {
        public string CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CPhone { get; set; }
        public string CAccount { get; set; }
        public string CEmail { get; set; }
        public string CPassWord { get; set; }
        public DateTime? CBirth { get; set; }
        public DateTime CAddDate { get; set; }
        public string CAddress { get; set; }
        public string CNotes { get; set; }
    }
}