// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebSiteTest.Areas.ProductsManager.Models
{
    public partial class Employees
    {
        public Employees()
        {
            Purchase = new HashSet<Purchase>();
        }

        public string EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeePhone { get; set; }
        public string EmployeeEmail { get; set; }
        public string EmployeePassWord { get; set; }
        public DateTime? EmployeeBirth { get; set; }
        public DateTime EmployeeHireDate { get; set; }
        public string EmployeeAddress { get; set; }
        public string EmployeeNotes { get; set; }

        public virtual ICollection<Purchase> Purchase { get; set; }
    }
}