// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebSiteTest.Areas.ProductsManager.Models
{
    public partial class OrderDetail
    {
        public string OrderId { get; set; }
        public string ProductId { get; set; }
        public int ProductQty { get; set; }
        public int ProductUnitPrice { get; set; }

        public virtual Orders Order { get; set; }
        public virtual Products Product { get; set; }
    }
}