// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebSiteTest.Areas.ProductsManager.Models
{
    public partial class Orders
    {
        //Orders
        public string OrderId { get; set; }
        public string CustomerId { get; set; }
        public string EmployeeId { get; set; }
        public DateTime OrderOnDate { get; set; }
        public DateTime ShipDate { get; set; }
        public string OrderStatus { get; set; }
        public string ShipAddress { get; set; }
        public string ShippingMethod { get; set; }

        public virtual OrderDetail OrderDetail { get; set; }
    }
}