// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebSiteTest.Areas.ProductsManager.Models
{
    public partial class Purchase
    {
        public string PurchaseId { get; set; }
        public DateTime PurchaseDate { get; set; }
        public string EmployeeId { get; set; }
        public string SupplierId { get; set; }

        public virtual Employees Employee { get; set; }
        public virtual Suppliers Supplier { get; set; }
        public virtual PurchaseDetail PurchaseDetail { get; set; }
    }
}