// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebSiteTest.Areas.ProductsManager.Models
{
    public partial class PurchaseDetail
    {
        public string PurchaseId { get; set; }
        public string ProductId { get; set; }
        public string ProductQty { get; set; }
        public string ProductUnitPrice { get; set; }

        public virtual Purchase Purchase { get; set; }
    }
}