// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebSiteTest.Areas.ProductsManager.Models
{
    public partial class Suppliers
    {
        public Suppliers()
        {
            Purchase = new HashSet<Purchase>();
        }

        public string SupplierId { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string ContactPerson { get; set; }
        public string Email { get; set; }
        public string Country { get; set; }

        public virtual ICollection<Purchase> Purchase { get; set; }
    }
}